version: 0.2

env:
  variables:
    key: "value"
    key: "value"
            
phases:
  install:
    commands:
      - apt-get update
      - apt-get upgrade -y
  pre_build:
    commands:
      # https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/troubleshooting.html#troubleshooting-utf-8
      - export LC_ALL="en_US.UTF-8"
      - locale-gen en_US en_US.UTF-8
      - dpkg-reconfigure locales

      - mv ${CODEBUILD_SRC_DIR_script}/* .
      - bundle install
      - mv ${CODEBUILD_SRC_DIR_data}/* .
  build:
    commands:
      - ruby make_cv.rb -s style.light.txt -o output.pdf
artifacts:
  files:
    - output.pdf
